spring.application.name=Tienda-Web-Arca

# URL de la base de datos MySQL
spring.datasource.url=jdbc:mysql://arcadb.cvyqgqcugeq7.sa-east-1.rds.amazonaws.com:3306/arcadb
spring.datasource.username=admin
spring.datasource.password=Independiente5$
# spring.datasource.url=jdbc:mysql://127.0.0.1:3306/arcadb
# spring.datasource.username=santi
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Habilitar JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true